[package]
name = "auto-sql-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.3"
proc-macro-crate.workspace = true
proc-macro2.workspace = true
quote = { workspace = true }
syn = { workspace = true, features = ["full", "visit-mut"] }
